apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-location-canary
  namespace: production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-location
        env: canary
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - image: gcr.io/absolute-text-251105/piggy1-location:v9
        name: piggyback-prod-runner-location
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/secret.json
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-location
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8080
status: {}
