apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-location-canary
  namespace: production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-location
        env: canary
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - image: gcr.io/omega-palace-254907/piggy1-location:v10
        name: piggyback-prod-runner-location
        env:
          - name: JASYPT_ENCRYPTOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jasypt-password
                key: password
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-location
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8080
status: {}
